# -*- coding: utf-8 -*-
"""Expriment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Ih0nxka8tbuEDzn9nzzWejfNqUyWER1
"""

a=int(input("Enter the number"))
b=int(input("Enter the number"))
c=a+b
print(c)